update logging part 34 (into main) (#1399)
progress on #1268 

I have a compiler error not yet resolved.

```java
C:\project\opendcs\java\opendcs\src\main\java\decodes\xml\jdbc\XmlOpenDcsDatabaseWrapper.java:33: error: method getSettings in class SimpleOpenDcsDatabaseWrapper cannot be applied to given types;
            return Optional.of((T)new EnumXmlDao(getSettings(DecodesSettings.class).get(), enumCache));
                                                 ^
  required: Class<T>
  found: Class<DecodesSettings>
  reason: inference variable T has incompatible bounds
    equality constraints: DecodesSettings
    lower bounds: OpenDcsSettings
    lower bounds: OpenDcsSettings
  where T is a type-variable:
    T extends OpenDcsSettings declared in method <T>getSettings(Class<T>)